python protocolo_parteMalha.py --sigma 0.0000275 --nome_arquivo resultadoSigmaX1.375.txt --output_dir_save outputs/save2fibroses_sigmax1.375/ --output_dir_restore outputs/restore2fibroses_sigmax1.375/ --dir_protocolo outputs/save2fibroses_sigmax1.375/
python protocolo_parteMalha.py --sigma 0.00003 --nome_arquivo resultadoSigmaX1.5.txt --output_dir_save outputs/save2fibroses_sigmax1.5/ --output_dir_restore outputs/restore2fibroses_sigmax1.5/ --dir_protocolo outputs/save2fibroses_sigmax1.5/
python protocolo_parteMalha.py --sigma 0.0000325 --nome_arquivo resultadoSigmaX1.625.txt --output_dir_save outputs/save2fibroses_sigmax1.625/ --output_dir_restore outputs/restore2fibroses_sigmax1.625/ --dir_protocolo outputs/save2fibroses_sigmax1.625
python protocolo_parteMalha.py --sigma 0.000035 --nome_arquivo resultadoSigmaX1.75.txt --output_dir_save outputs/save2fibroses_sigmax1.75/ --output_dir_restore outputs/restore2fibroses_sigmax1.75/ --dir_protocolo outputs/save2fibroses_sigmax1.75
python protocolo_parteMalha.py --sigma 0.0000375 --nome_arquivo resultadoSigmaX1.875.txt --output_dir_save outputs/save2fibroses_sigmax1.875/ --output_dir_restore outputs/restore2fibroses_sigmax1.875/ --dir_protocolo outputs/save2fibroses_sigmax1.875
python protocolo_parteMalha.py --sigma 0.0000425 --nome_arquivo resultadoSigmaX2.125.txt --output_dir_save outputs/save2fibroses_sigmax2.125/ --output_dir_restore outputs/restore2fibroses_sigmax2.125/ --dir_protocolo outputs/save2fibroses
_sigmax2.125
python protocolo_parteMalha.py --sigma 0.000045 --nome_arquivo resultadoSigmaX2.25.txt --output_dir_save outputs/save2fibroses_sigmax2.25/ --output_dir_restore outputs/restore2fibroses_sigmax2.25/ --dir_protocolo outputs/save2fibroses_sigmax2.25
python protocolo_parteMalha.py --sigma 0.0000475 --nome_arquivo resultadoSigmaX2.375.txt --output_dir_save outputs/save2fibroses_sigmax2.375/ --output_dir_restore outputs/restore2fibroses_sigmax2.375/ --dir_protocolo outputs/save2fibroses_sigmax2.375
python protocolo_parteMalha.py --sigma 0.00005 --nome_arquivo resultadoSigmaX2.5.txt --output_dir_save outputs/save2fibroses_sigmax2.5/ --output_dir_restore outputs/restore2fibroses_sigmax2.5/ --dir_protocolo outputs/save2fibroses_sigmax2.5
bin/MonoAlg3D -c example_configs/s1mulacaoParteMalha.ini
