python protocolo_parteMalha.py --sigma 0.0000224 --output_dir_save outputs/SaveSigma1/ --output_dir_restore outputs/RestoreSigma1/ --nome_arquivo rSigma1.txt --dir_protocolo outputs/SaveSigma1/
python protocolo_parteMalha.py --sigma 0.0000248 --output_dir_save outputs/SaveSigma2/ --output_dir_restore outputs/RestoreSigma2/ --nome_arquivo rSigma2.txt --dir_protocolo outputs/SaveSigma2/
python protocolo_parteMalha.py --sigma 0.0000272 --output_dir_save outputs/SaveSigma3/ --output_dir_restore outputs/RestoreSigma3/ --nome_arquivo rSigma3.txt --dir_protocolo outputs/SaveSigma3/
python protocolo_parteMalha.py --sigma 0.0000296 --output_dir_save outputs/SaveSigma4/ --output_dir_restore outputs/RestoreSigma4/ --nome_arquivo rSigma4.txt --dir_protocolo outputs/SaveSigma4/
python protocolo_parteMalha.py --sigma 0.0000320 --output_dir_save outputs/SaveSigma5/ --output_dir_restore outputs/RestoreSigma5/ --nome_arquivo rSigma5.txt --dir_protocolo outputs/SaveSigma5/
python protocolo_parteMalha.py --sigma 0.0000344 --output_dir_save outputs/SaveSigma6/ --output_dir_restore outputs/RestoreSigma6/ --nome_arquivo rSigma6.txt --dir_protocolo outputs/SaveSigma6/
python protocolo_parteMalha.py --sigma 0.0000368 --output_dir_save outputs/SaveSigma7/ --output_dir_restore outputs/RestoreSigma7/ --nome_arquivo rSigma7.txt --dir_protocolo outputs/SaveSigma7/
python protocolo_parteMalha.py --sigma 0.0000392 --output_dir_save outputs/SaveSigma8/ --output_dir_restore outputs/RestoreSigma8/ --nome_arquivo rSigma8.txt --dir_protocolo outputs/SaveSigma8/
python protocolo_parteMalha.py --sigma 0.0000416 --output_dir_save outputs/SaveSigma9/ --output_dir_restore outputs/RestoreSigma9/ --nome_arquivo rSigma9.txt --dir_protocolo outputs/SaveSigma9/
python protocolo_parteMalha.py --sigma 0.0000440 --output_dir_save outputs/SaveSigma10/ --output_dir_restore outputs/RestoreSigma10/ --nome_arquivo rSigma10.txt --dir_protocolo outputs/SaveSigma10/
python protocolo_parteMalha.py --sigma 0.0000464 --output_dir_save outputs/SaveSigma11/ --output_dir_restore outputs/RestoreSigma11/ --nome_arquivo rSigma11.txt --dir_protocolo outputs/SaveSigma11/
python protocolo_parteMalha.py --sigma 0.0000488 --output_dir_save outputs/SaveSigma12/ --output_dir_restore outputs/RestoreSigma12/ --nome_arquivo rSigma12.txt --dir_protocolo outputs/SaveSigma12/
python protocolo_parteMalha.py --sigma 0.0000512 --output_dir_save outputs/SaveSigma13/ --output_dir_restore outputs/RestoreSigma13/ --nome_arquivo rSigma13.txt --dir_protocolo outputs/SaveSigma13/
python protocolo_parteMalha.py --sigma 0.0000536 --output_dir_save outputs/SaveSigma14/ --output_dir_restore outputs/RestoreSigma14/ --nome_arquivo rSigma14.txt --dir_protocolo outputs/SaveSigma14/
python protocolo_parteMalha.py --sigma 0.0000560 --output_dir_save outputs/SaveSigma15/ --output_dir_restore outputs/RestoreSigma15/ --nome_arquivo rSigma15.txt --dir_protocolo outputs/SaveSigma15/
python protocolo_parteMalha.py --sigma 0.0000584 --output_dir_save outputs/SaveSigma16/ --output_dir_restore outputs/RestoreSigma16/ --nome_arquivo rSigma16.txt --dir_protocolo outputs/SaveSigma16/
python protocolo_parteMalha.py --sigma 0.0000608 --output_dir_save outputs/SaveSigma17/ --output_dir_restore outputs/RestoreSigma17/ --nome_arquivo rSigma17.txt --dir_protocolo outputs/SaveSigma17/
python protocolo_parteMalha.py --sigma 0.0000632 --output_dir_save outputs/SaveSigma18/ --output_dir_restore outputs/RestoreSigma18/ --nome_arquivo rSigma18.txt --dir_protocolo outputs/SaveSigma18/
python protocolo_parteMalha.py --sigma 0.0000656 --output_dir_save outputs/SaveSigma19/ --output_dir_restore outputs/RestoreSigma19/ --nome_arquivo rSigma19.txt --dir_protocolo outputs/SaveSigma19/
python protocolo_parteMalha.py --sigma 0.0000680 --output_dir_save outputs/SaveSigma20/ --output_dir_restore outputs/RestoreSigma20/ --nome_arquivo rSigma20.txt --dir_protocolo outputs/SaveSigma20/
python protocolo_parteMalha.py --sigma 0.0000704 --output_dir_save outputs/SaveSigma21/ --output_dir_restore outputs/RestoreSigma21/ --nome_arquivo rSigma21.txt --dir_protocolo outputs/SaveSigma21/
python protocolo_parteMalha.py --sigma 0.0000728 --output_dir_save outputs/SaveSigma22/ --output_dir_restore outputs/RestoreSigma22/ --nome_arquivo rSigma22.txt --dir_protocolo outputs/SaveSigma22/
python protocolo_parteMalha.py --sigma 0.0000752 --output_dir_save outputs/SaveSigma23/ --output_dir_restore outputs/RestoreSigma23/ --nome_arquivo rSigma23.txt --dir_protocolo outputs/SaveSigma23/
python protocolo_parteMalha.py --sigma 0.0000776 --output_dir_save outputs/SaveSigma24/ --output_dir_restore outputs/RestoreSigma24/ --nome_arquivo rSigma24.txt --dir_protocolo outputs/SaveSigma24/
python protocolo_parteMalha.py --sigma 0.0000800 --output_dir_save outputs/SaveSigma25/ --output_dir_restore outputs/RestoreSigma25/ --nome_arquivo rSigma25.txt --dir_protocolo outputs/SaveSigma25/
python protocolo_parteMalha.py --sigma 0.0000824 --output_dir_save outputs/SaveSigma26/ --output_dir_restore outputs/RestoreSigma26/ --nome_arquivo rSigma26.txt --dir_protocolo outputs/SaveSigma26/
python protocolo_parteMalha.py --sigma 0.0000848 --output_dir_save outputs/SaveSigma27/ --output_dir_restore outputs/RestoreSigma27/ --nome_arquivo rSigma27.txt --dir_protocolo outputs/SaveSigma27/
python protocolo_parteMalha.py --sigma 0.0000872 --output_dir_save outputs/SaveSigma28/ --output_dir_restore outputs/RestoreSigma28/ --nome_arquivo rSigma28.txt --dir_protocolo outputs/SaveSigma28/
python protocolo_parteMalha.py --sigma 0.0000896 --output_dir_save outputs/SaveSigma29/ --output_dir_restore outputs/RestoreSigma29/ --nome_arquivo rSigma29.txt --dir_protocolo outputs/SaveSigma29/
python protocolo_parteMalha.py --sigma 0.0000920 --output_dir_save outputs/SaveSigma30/ --output_dir_restore outputs/RestoreSigma30/ --nome_arquivo rSigma30.txt --dir_protocolo outputs/SaveSigma30/
python protocolo_parteMalha.py --sigma 0.0000944 --output_dir_save outputs/SaveSigma31/ --output_dir_restore outputs/RestoreSigma31/ --nome_arquivo rSigma31.txt --dir_protocolo outputs/SaveSigma31/
python protocolo_parteMalha.py --sigma 0.0000968 --output_dir_save outputs/SaveSigma32/ --output_dir_restore outputs/RestoreSigma32/ --nome_arquivo rSigma32.txt --dir_protocolo outputs/SaveSigma32/
python protocolo_parteMalha.py --sigma 0.0000992 --output_dir_save outputs/SaveSigma33/ --output_dir_restore outputs/RestoreSigma33/ --nome_arquivo rSigma33.txt --dir_protocolo outputs/SaveSigma33/
python protocolo_parteMalha.py --sigma 0.0001016 --output_dir_save outputs/SaveSigma34/ --output_dir_restore outputs/RestoreSigma34/ --nome_arquivo rSigma34.txt --dir_protocolo outputs/SaveSigma34/
python protocolo_parteMalha.py --sigma 0.0001040 --output_dir_save outputs/SaveSigma35/ --output_dir_restore outputs/RestoreSigma35/ --nome_arquivo rSigma35.txt --dir_protocolo outputs/SaveSigma35/
python protocolo_parteMalha.py --sigma 0.0001064 --output_dir_save outputs/SaveSigma36/ --output_dir_restore outputs/RestoreSigma36/ --nome_arquivo rSigma36.txt --dir_protocolo outputs/SaveSigma36/
python protocolo_parteMalha.py --sigma 0.0001088 --output_dir_save outputs/SaveSigma37/ --output_dir_restore outputs/RestoreSigma37/ --nome_arquivo rSigma37.txt --dir_protocolo outputs/SaveSigma37/
python protocolo_parteMalha.py --sigma 0.0001112 --output_dir_save outputs/SaveSigma38/ --output_dir_restore outputs/RestoreSigma38/ --nome_arquivo rSigma38.txt --dir_protocolo outputs/SaveSigma38/
python protocolo_parteMalha.py --sigma 0.0001136 --output_dir_save outputs/SaveSigma39/ --output_dir_restore outputs/RestoreSigma39/ --nome_arquivo rSigma39.txt --dir_protocolo outputs/SaveSigma39/
python protocolo_parteMalha.py --sigma 0.0001160 --output_dir_save outputs/SaveSigma40/ --output_dir_restore outputs/RestoreSigma40/ --nome_arquivo rSigma40.txt --dir_protocolo outputs/SaveSigma40/
python protocolo_parteMalha.py --sigma 0.0001184 --output_dir_save outputs/SaveSigma41/ --output_dir_restore outputs/RestoreSigma41/ --nome_arquivo rSigma41.txt --dir_protocolo outputs/SaveSigma41/
python protocolo_parteMalha.py --sigma 0.0001208 --output_dir_save outputs/SaveSigma42/ --output_dir_restore outputs/RestoreSigma42/ --nome_arquivo rSigma42.txt --dir_protocolo outputs/SaveSigma42/
python protocolo_parteMalha.py --sigma 0.0001232 --output_dir_save outputs/SaveSigma43/ --output_dir_restore outputs/RestoreSigma43/ --nome_arquivo rSigma43.txt --dir_protocolo outputs/SaveSigma43/
python protocolo_parteMalha.py --sigma 0.0001256 --output_dir_save outputs/SaveSigma44/ --output_dir_restore outputs/RestoreSigma44/ --nome_arquivo rSigma44.txt --dir_protocolo outputs/SaveSigma44/
python protocolo_parteMalha.py --sigma 0.0001280 --output_dir_save outputs/SaveSigma45/ --output_dir_restore outputs/RestoreSigma45/ --nome_arquivo rSigma45.txt --dir_protocolo outputs/SaveSigma45/
python protocolo_parteMalha.py --sigma 0.0001304 --output_dir_save outputs/SaveSigma46/ --output_dir_restore outputs/RestoreSigma46/ --nome_arquivo rSigma46.txt --dir_protocolo outputs/SaveSigma46/
python protocolo_parteMalha.py --sigma 0.0001328 --output_dir_save outputs/SaveSigma47/ --output_dir_restore outputs/RestoreSigma47/ --nome_arquivo rSigma47.txt --dir_protocolo outputs/SaveSigma47/
python protocolo_parteMalha.py --sigma 0.0001352 --output_dir_save outputs/SaveSigma48/ --output_dir_restore outputs/RestoreSigma48/ --nome_arquivo rSigma48.txt --dir_protocolo outputs/SaveSigma48/
python protocolo_parteMalha.py --sigma 0.0001376 --output_dir_save outputs/SaveSigma49/ --output_dir_restore outputs/RestoreSigma49/ --nome_arquivo rSigma49.txt --dir_protocolo outputs/SaveSigma49/
python protocolo_parteMalha.py --sigma 0.0001400 --output_dir_save outputs/SaveSigma50/ --output_dir_restore outputs/RestoreSigma50/ --nome_arquivo rSigma50.txt --dir_protocolo outputs/SaveSigma50/

